openapi: 3.0.1
info:
  title: Reservations Service API
  description: Reservations from GoOutSafe with Microservices
  version: "0.1"
servers:
- url: /
paths:
  /customer_reservations/{user_id}:
    get:
      tags:
      - Reservations
      summary: Get the future reservations of the user specified by the given user_id
      operationId: reservation_microservice.customer_reservations.get_reservations
      parameters:
      - name: user_id
        in: path
        description: User's Unique identifier
        required: true
        schema:
          pattern: ^[a-zA-Z0-9-]+$
          type: string
      responses:
        200:
          description: Return the future reservations of the user
          content:
            application/json:
              schema:
                type: object
                properties:
                  pets:
                    type: array
                    items:
                      $ref: '#/components/schemas/Reservation'
        404:
          description: No reservations associated with the given user_id
          content: {}
  /customer_reservations/{user_id}/restaurant/{restaurant_id}:
    get:
      tags:
      - Reservations
      summary: Get the reservation performed by the user specified by user_id at the restaurant specified by restaurant_id
      operationId: reservation_microservice.customer_reservations.get_reservations_by_restaurant
      parameters:
      - name: user_id
        in: path
        description: User's unique identifier
        required: true
        schema:
          pattern: ^[a-zA-Z0-9-]+$
          type: string
      - name: restaurant_id
        in: path
        description: Restaurant's unique identifier
        required: true
        schema:
          pattern: ^[a-zA-Z0-9-]+$
          type: string
      - name: uid
        in: query
        description: filters reservations by user_id different from the given one. Must be used with both start_time and end_time.
        required: false
        schema:
          type: string
          enum:
            - diff
      - name: start_time
        in: query
        description: The start time of the entrance_time for the wanted reservations. Can be used both in combination with end_time or alone.
        required: false
        schema:
          type: string
          format: date-time
      - name: end_time
        in: query
        description: The end time of the entrance_time for the wanted reservations. Must be used with start_time.
        schema:
          type: string
          format: date-time
      responses:
        200:
          description: Returns the reservations
          content:
            application/json:
              schema:
                type: object
                properties:
                  pets:
                    type: array
                    items:
                      $ref: '#/components/schemas/Reservation'
        400:
          description: parameters error
          content: {}
        404:
          description: no reservations associated to the given user_id or restaurant_id
          content: {}
        
  /customer_reservation/{reservation_id}:
    delete:
      tags:
      - Reservations
      summary: Delete the reservation specified by the given reservation_id
      operationId: reservation_microservice.customer_reservations.delete_user_reservation
      parameters:
      - name: reservation_id
        in: path
        description: Reservation's Unique identifier
        required: true
        schema:
          pattern: ^[a-zA-Z0-9-]+$
          type: string
      responses:
        204:
          description: Reservation deleted correctly

        401:
          description: You must be authorized to perform this operation
          content: {}
              
        404:
          description: The specified reservation does not exist
          content: {}
    put:
      tags:
      - Reservations
      summary: Update the reservation specified by the given reservation_id
      operationId: reservation_microservice.customer_reservations.update_user_reservation
      parameters:
      - name: reservation_id
        in: path
        description: Reservation's Unique identifier
        required: true
        schema:
          pattern: ^[a-zA-Z0-9-]+$
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                new_reservation_time:
                  type: string
                  format: date-time
                  description: the new date and time of the reservation
                new_seats:
                  type: integer
                  description: the new number of reserved seats
      responses:
        200:
          description: OK
          content: {}
        401: 
          description: You must be authorized to perform this operation
          content: {}
        404: 
          description: The specified reservation does not exist
          content: {}
        500:
          description: service error
          content: {}
  /reservations/{restaurant_id}:
    get:
      tags:
      - Reservations
      summary: get the reservations associated to the restaurant specified by restaurant_id
      operationId: reservation_microservice.restaurant_reservations.get_restaurant_reservations
      parameters:
      - name: restaurant_id
        in: path
        description: Restaurant's unique identifier
        required: true
        schema:
          pattern: ^[a-zA-Z0-9-]+$
          type: string
      responses:
        200:
          description: Return the reservations of the restaurant
          content:
            application/json:
              schema:
                type: object
                properties:
                  pets:
                    type: array
                    items:
                      $ref: '#/components/schemas/Reservation'
        404:
          description: The restaurant specified by restaurant_id has no associated reservations
          content: {}
        500:
          description: service error
          content: {}
    delete:
      tags:
      - Reservations
      summary: Delete all the future reservations associated to the restaurant specified by restaurant_id
      operationId: reservation_microservice.restaurant_reservations.delete_restaurant_reservations
      parameters:
      - name: restaurant_id
        in: path
        description: Restaurant's unique identifier
        required: true
        schema:
            pattern: ^[a-zA-Z0-9-]+$
            type: string
      responses:
        204:
          description: Reservations deleted correctly
        404:
          description: The restaurant specified by restaurant_id has no associated reservations
          content: {}
        500:
          description: service error
          content: {}

  /reserve:
    post:
      tags:
      - Reservations
      summary: Add a new reservation
      operationId: reservation_microservice.customer_reservations.reserve
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: unique identifier of the user performing the reservation
                restaurant_id:
                  type: integer
                  description: unique identifier of the reserved restaurant
                reservation_time: 
                  type: string
                  format: date-time
                  description: date and time of the reservation
                seats:
                  type: integer
                  description: the number of reserved seats
      responses:
        200:
          description: Reservation added correctly
          content: {}
        401:
          description: You must be authorized to perform this operation
          content: {}
        500:
          description: Error in service
          content: {}
components:
  schemas:
    Reservation:
      required:
      - id
      - user_id
      - restaurant_id
      - reservation_time
      - status
      - table_no
      - seats
      - entrance_time
      - exit_time
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier of the reservation
          readOnly: true
          example: 123
        user_id:
          type: integer
          description: Unique identifier of the user performing the reservation
          example: 12
        restaurant_id:
          type: integer
          description: Unique identifier of the restaurant to be reserved
          example: 67
        reservation_time:
          type: string
          format: date-time
          description: Date and time of the reservation
        status:
          type: string
          description: The reservation status
          enum:
            - Declined
            - Pending
            - Accepted
            - Seated
            - Done
          example: Accepted
        table_no:
          type: integer
          description: Unique identifier of the reserved table
          example: 124
        seats:
          type: integer
          description: The number of seats of the reservation 
          example: 6
        entrance_time:
          type: string
          format: date-time
          description: The entrance time of the customer for the reservation
          nullable: true
          example:
        exit_time:
          type: string
          format: date-time
          description: The exit time of the customer for the reservation
          nullable: true
